job1_deploy_all_qualif:
  stage: deploy
  tags: 
    - qualif
  script:
    - rm -rf /appli/informatiquelycee/web
    - cp -R . /appli/informatiquelycee/web
  only:
    - master
job2_deploy_all_prod:
  stage: deploy
  tags:
    - prod
  script:
    - rm -rf /appli/informatiquelycee/web
    - cp -R . /appli/informatiquelycee/web
  when: manual